Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

/*
 * Logic:
 * 1. brute force
 * 2. sort
 * 3. hashmap (maintain letter count)
 * 4. array of 26 length (maintain letter count)
 */

public class Solution {
    public char findTheDifference(String s, String t) {
        int[] arr = new int[26];
        
        for(int i=0; i<s.length(); i++)
            arr[s.charAt(i)-'a']++;
            
        for(int j=0; j<t.length(); j++)
            arr[t.charAt(j)-'a']--;
        int k = 0;    
        for(; k<arr.length; k++){
            if(arr[k]!=0)
                break;
        }
        return (char)('a'+k);
    }
}